spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sb-bank-cards
    username: user
    password: password
  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    # https://habr.com/ru/post/440734/
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true